### ISSUE TITLE
Request: Leverage package extensions

### ISSUE THREAD

**Issue by jakobnissen** [JuliaPlots/UnicodePlots.jl#331]
In the upcoming Julia 1.9, dependencies can be added as optional, such that they are only loaded if a set of other packages are also loaded in the same session.

UnicodePlots is quite dependency-heavy (see #291), leading to high latency (see #324) but the deps can't just be removed as this would remove features in some cases.
Using package extensions could significantly improve loading times and latency for the large majority of users, while still providing the features needed by the minority.

Package extensions are non-breaking on earlier Julia versions.

**Comment by t-bltg** [comment]
I'd like to correct a few things here:

- https://github.com/JuliaPlots/UnicodePlots.jl/issues/291 was partially solved by https://github.com/JuliaPlots/UnicodePlots.jl/pull/294, and we need `ColorSchemes` to handle colormaps so I'd suggest commenting in https://github.com/JuliaGraphics/ColorVectorSpace.jl/issues/184 in order to get rid of `SpecialFunctions`;
- https://github.com/JuliaPlots/UnicodePlots.jl/issues/324 is not at all complaining about dependency induced latency, rather latency induced by `UnicodePlots` through the precompilation scenario.

I find it rather cumbersome to request from a user to load `ColorSchemes` to use basic plot features such as colormaps (used by `contourplot`, `surfaceplot` and `heatmap`) before using `UnicodePlots`.

That being said, we can support package extensions for the single `@require` line present in `__init__`: https://github.com/JuliaPlots/UnicodePlots.jl/blob/c7f2f95b1f729dc254c735e2a64a1fde5698b39d/src/UnicodePlots.jl#L126, but I must admit this isn't on my todo list (there currently is no added value to doing this except making the code more complex, and of course modernize it as `julia` enhances). We could maybe wait for the next LTS and support only julia versions with package extensions thus dropping the `Requires` usage at this precise moment.

**Comment by t-bltg** [comment]
See https://github.com/JuliaGraphics/ColorVectorSpace.jl/pull/186 for the proposal to make `SpecialFunctions` optional in `ColorVectorSpace`.

**Comment by mcabbott** [comment]
From #324 StaticArrays and Unitful seem to take a long time. Are SArrays used internally? Quick searches did not tell me much. 

But Unitful seems to be fairly isolated, might also be a good candidate?

https://github.com/JuliaPlots/UnicodePlots.jl/blob/c7f2f95b1f729dc254c735e2a64a1fde5698b39d/src/interface/lineplot.jl#L188-L190

**Comment by t-bltg** [comment]
> Are SArrays used internally? Quick searches did not tell me much.

I knew this felt like déjà vu: https://github.com/JuliaPlots/UnicodePlots.jl/issues/222#issuecomment-1331494589 ;)

> But Unitful seems to be fairly isolated, might also be a good candidate?

It's actually used in two other places:
https://github.com/JuliaPlots/UnicodePlots.jl/blob/master/src/common.jl#L386-L388
and
https://github.com/JuliaPlots/UnicodePlots.jl/blob/master/src/interface/scatterplot.jl#L137-L163

As you said this is a good candidate too. You likely have `Unitful` loaded when you plot `Quantities`.
One drawback of using extensions is that it fragments the code so I have to think a bit more about the implementation in https://github.com/JuliaPlots/UnicodePlots.jl/pull/332.

**Comment by mcabbott** [comment]
> déjà vu

Sorry! I searched but clearly not everywhere...

#332 looks great.

**Comment by t-bltg** [comment]
While implementing 3d plots, I didn't take loading time into account and thought using static matrices was a good idea. So I didn't benchmark using regular matrices vs StaticArrays ones. I can imagine the case where you plot the 3d results from a pde evolving in time thus using a fixed model-view-projection matrix. I can also imagine rotating stuff (azimuth and elevation) and generating a gif out of it (changing MVP matrix), so there are multiple use cases.

I'm all in favour of removing the StaticArrays dependency for 3d plots if the performance impact is negligible (a few percents would be acceptable).

I'm marking this on my Todo list (we need a plausible real case usage benchmark).
