### ISSUE TITLE
Consider the TerminalImageViewer approach

### ISSUE THREAD

**Issue by waldyrious** [JuliaPlots/UnicodePlots.jl#50]
It may be an interesting technique to adapt: https://github.com/stefanhaustein/TerminalImageViewer#terminalimageviewer

**Comment by Evizero** [comment]
that does look very impressive yes. but no license means no peaking. I have also seen a julia package that does pretty cool heat maps using 256 colors. Also something I would like to get around to at some point

**Comment by waldyrious** [comment]
I'll ask the author to add a license.

**Comment by waldyrious** [comment]
> a julia package that does pretty cool heat maps using 256 colors

Which one, may I ask?

**Comment by waldyrious** [comment]
Well, [that was quick](https://github.com/stefanhaustein/TerminalImageViewer/issues/2) :) There's a [license](https://github.com/stefanhaustein/TerminalImageViewer/blob/master/LICENSE) now in the repo.

**Comment by Evizero** [comment]
That is pretty cool. A port may even deserve it's own package

**Comment by Evizero** [comment]
> Which one, may I ask?

I actually can't seem to find it any more. maybe it is gone or maybe genius me forgot to bookmark it

**Comment by waldyrious** [comment]
I think I found it! Could it be https://github.com/meggart/ImageTerm.jl?

**Comment by Evizero** [comment]
yes, that was the one. I have an idea how to do coloured heatmaps with twice the resolution, but I do not know when I will get around to implement them. I kinda would like to do them in a way that Plots.jl can benefit, since I am guessing that is the biggest portion of the UnicodePlots userbase. I am also considering porting the TerminalImageViewer to a dedicated Julia package, since it has a nice license that would allow for that.

I have no ETA on any of those plans, but I hope I'll take at least one of them on in the next two weeks

**Comment by t-bltg** [comment]
Closing in favor of https://github.com/JuliaPlots/UnicodePlots.jl/issues/153.
